/**
 * Klimbibliotheek: de beklimmingen van de Benelux en grensstreek met
 * indicatieve statistieken. Cijfers zijn afgerond en gemarkeerd als indicatief
 * (bronnen: wielerflits, fiets.nl, climbfinder) — het bord ter plekke telt.
 */

import type { EventCountry } from "./calendar.ts";

export type { EventCountry } from "./calendar.ts";

export type Surface = "asfalt" | "kassei" | "keien";

export interface Climb {
  id: string;
  name: string;
  country: EventCountry;
  place: string;
  /** lengte in meters (indicatief) */
  lengthM: number;
  /** gemiddeld stijgingspercentage (indicatief) */
  avgPct: number;
  /** steilste stuk (indicatief) */
  maxPct: number;
  /** hoogteverschil in meters (indicatief) */
  elevationM: number;
  surface: Surface;
  /** hoogte van de top in meters boven zeeniveau (voor de FIETS-index) */
  summitM: number;
  /** indicatieve coordinaten van de top (voor kaart en nabijheid) */
  lat: number;
  lon: number;
  /** openingsperiode, indicatief */
  seizoen?: string,
  note: string;
  /** kant-en-klare zin voor de route-assistent */
  prompt: string;
}

export const CLIMBS: Climb[] = [
  { id: "cauberg", name: "Cauberg", country: "NL", place: "Valkenburg", lengthM: 785, avgPct: 7.8, maxPct: 13.2, elevationM: 58, summitM: 130, lat: 50.8646, lon: 5.829, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "De bekendste klim van Nederland: Amstel Gold Race-decidé, zwaarste 150 meter aan 13%.", prompt: "Bouw een fiets- of motorrondrit vanaf Valkenburg over de Cauberg, zo'n 60 km, mooie wegen" },
  { id: "camerig", name: "Camerig", country: "NL", place: "Epen", lengthM: 4400, avgPct: 5, maxPct: 12, elevationM: 165, summitM: 250, lat: 50.7708, lon: 5.9227, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "Langste en volgens velen mooiste klim van het land, met vergezicht over het Geuldal.", prompt: "Plan een rit door Zuid-Limburg over de Camerig bij Epen, ongeveer 80 km" },
  { id: "kromhagerweg", name: "Kromhagerweg", country: "NL", place: "Epen", lengthM: 700, avgPct: 9.5, maxPct: 11.1, elevationM: 60, summitM: 230, lat: 50.769, lon: 5.933, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "Korte maar gemene muur in de streek van de Camerig — echt benenwerk.", prompt: "Rondrit Zuid-Limburg met de Kromhagerweg bij Epen erin, 70 km" },
  { id: "loorberg", name: "Loorberg", country: "NL", place: "Slenaken", lengthM: 900, avgPct: 9, maxPct: 17, summitM: 205, lat: 50.7817, lon: 5.9, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", elevationM: 70, note: "Steile beklimming naar Slenaken; de combinatie met de Camerig is een klassieker.", prompt: "Fietsrit over de Loorberg en de Camerig, start in Gulpen, 75 km" },
  { id: "eyserbosweg", name: "Eyserbosweg", country: "NL", place: "Eys", lengthM: 900, avgPct: 9, maxPct: 16, summitM: 200, lat: 50.8103, lon: 5.906, surface: "keien", seizoen: "hele jaar — keien glad na regen", elevationM: 70, note: "Keien uit 1948 in het Limburgse heuvelland — Amstel Gold Race-terrein.", prompt: "Motor- of fietstocht langs de Eyserbosweg bij Eys, 70 km rondrit" },
  { id: "vaalserberg", name: "Vaalserberg", country: "NL", place: "Vaals", lengthM: 2500, avgPct: 4, maxPct: 8, elevationM: 90, summitM: 322, lat: 50.754, lon: 6.0208, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "Het hoogste punt van Nederland (322 m) met drielandenpunt bovenop.", prompt: "Rondrit naar de Vaalserberg en het drielandenpunt, 65 km" },
  { id: "bemelerberg", name: "Bemelerberg", country: "NL", place: "Bemelen", lengthM: 650, avgPct: 5, maxPct: 9, elevationM: 35, summitM: 130, lat: 50.842, lon: 5.758, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "Korte klim tussen de witte wallen van de Bemelerberg: ideaal als opwarmer.", prompt: "Rit door het Bemelerheuvelland over de Bemelerberg, 55 km" },

  { id: "muur-geraardsbergen", name: "Muur van Geraardsbergen", country: "BE", place: "Geraardsbergen", lengthM: 475, avgPct: 9.7, maxPct: 16, elevationM: 45, summitM: 110, lat: 50.7699, lon: 3.876, surface: "kassei", seizoen: "hele jaar — kasseien het best bij droog weer", note: "De Muur van de Ronde: kassei, kapel en een steile muur die Vlaanderen definieert.", prompt: "Motorrit naar de Muur van Geraardsbergen en door de Vlaamse Ardennen, 120 km" },
  { id: "koppenberg", name: "Koppenberg", country: "BE", place: "Oudenaarde", lengthM: 600, avgPct: 11.6, maxPct: 22, elevationM: 64, summitM: 77, lat: 50.8127, lon: 3.582, surface: "kassei", seizoen: "hele jaar — kasseien het best bij droog weer", note: "De beruchtste kasseiklim van de Ronde: tot 22% over losse stenen.", prompt: "Ronde van Vlaanderen-rit over de Koppenberg en Paterberg vanaf Oudenaarde, 100 km" },
  { id: "paterberg", name: "Paterberg", country: "BE", place: "Kluisbergen", lengthM: 360, avgPct: 12.9, maxPct: 20, elevationM: 46, summitM: 83, lat: 50.7752, lon: 3.51, surface: "kassei", seizoen: "hele jaar — kasseien het best bij droog weer", note: "Korte, explosieve kasseiklim (gem. bijna 13%) in de Ronde van Vlaanderen.", prompt: "Vlaamse Ardennen-motorrit met de Paterberg en de Oude Kwaremont, 110 km" },
  { id: "la-redoute", name: "La Redoute", country: "BE", place: "Aywaille", lengthM: 1700, avgPct: 7.4, maxPct: 17, elevationM: 120, summitM: 300, lat: 50.468, lon: 5.672, surface: "asfalt", seizoen: "hele jaar — in de winter kan sneeuw liggen", note: "De beslissende klim van Luik-Bastenaken-Luik: steilste stuk op de plated sections.", prompt: "Ardennen-motorrit over La Redoute bij Aywaille, 140 km" },
  { id: "col-du-rosier", name: "Col du Rosier", country: "BE", place: "Spa → Francorchamps", lengthM: 4400, avgPct: 5, maxPct: 9, elevationM: 215, summitM: 480, lat: 50.515, lon: 5.86, surface: "asfalt", seizoen: "hele jaar — in de winter kan sneeuw liggen", note: "De langste beklimming van Wallonië, richting de streek van Spa-Francorchamps.", prompt: "Rit door de Ardennen over de Col du Rosier richting Spa, 150 km" },
  { id: "baraque-fraiture", name: "Baraque de Fraiture", country: "BE", place: "Vielsalm", lengthM: 3500, avgPct: 4.5, maxPct: 8, elevationM: 160, summitM: 652, lat: 50.254, lon: 5.748, surface: "asfalt", seizoen: "hele jaar — in de winter kan sneeuw liggen", note: "Hoogste punt van de Belgische wegen (652 m) — in de winter sneeuwzeker.", prompt: "Rit naar de Baraque de Fraiture, hoogste punt van België, 160 km" },

  { id: "schauinsland", name: "Schauinsland", country: "DE", place: "Freiburg im Breisgau", lengthM: 11500, avgPct: 6.6, maxPct: 12, elevationM: 760, summitM: 1240, lat: 47.913, lon: 7.899, surface: "asfalt", seizoen: "hele jaar — sneeuw mogelijk in de winter", note: "Legendarische Zwarte Woud-klim (11,5 km): het doel van elke Zuid-Duitse klimrit.", prompt: "Zwarte Woud-motorrit over de Schauinsland bij Freiburg, 200 km" },
  { id: "alpe-huez", name: "Alpe d'Huez", country: "FR", place: "Bourg d'Oisans", lengthM: 13800, avgPct: 8.1, maxPct: 13, elevationM: 1135, summitM: 1850, lat: 45.092, lon: 6.07, surface: "asfalt", seizoen: "hele jaar — de weg naar het skigebied wordt sneeuwvrij gehouden", note: "De beroemdste klim ter wereld: 21 genummerde haarspelden, gemiddeld 8,1% over 13,8 km.", prompt: "Motorrit door de Franse Alpen met de Alpe d'Huez en de Col du Galibier, 180 km" },
  { id: "galibier", name: "Col du Galibier", country: "FR", place: "Valloire", lengthM: 17000, avgPct: 6.9, maxPct: 10.5, elevationM: 1185, summitM: 2642, lat: 45.064, lon: 6.4076, surface: "asfalt", seizoen: "ca. juni–okt (wintergesloten)", note: "Mythische Tour-col op 2642 m; de tunnel dateert uit 1891, de topweg van 1976.", prompt: "Alpenrit over de Col du Galibier vanaf Valloire en door de Maurienne, 200 km" },
  { id: "tourmalet", name: "Col du Tourmalet", country: "FR", place: "Sainte-Marie-de-Campan", lengthM: 17200, avgPct: 7.4, maxPct: 10.2, elevationM: 1268, summitM: 2115, lat: 42.908, lon: 0.145, surface: "asfalt", seizoen: "ca. eind mei–okt (wintergesloten)", note: "De meest bereden col van de Tour (top 2115 m), met het Lacquet-plateau als beloning.", prompt: "Pyreneeën- of Alpenmix: rit over de Col du Tourmalet vanaf Sainte-Marie-de-Campan, 160 km" },
  { id: "izoard", name: "Col d'Izoard", country: "FR", place: "Briançon", lengthM: 14100, avgPct: 7.1, maxPct: 9.5, elevationM: 1001, summitM: 2360, lat: 44.82, lon: 6.735, surface: "asfalt", seizoen: "ca. mei–okt (wintergesloten)", note: "Casse Déserte boven de boomgrens: maanlandschap en Roubaix-herinneringen van Coppi en Bobet.", prompt: "Rit vanaf Briançon over de Col d'Izoard, 150 km" },
  { id: "stelvio", name: "Passo dello Stelvio", country: "IT", place: "Prato allo Stelvio", lengthM: 24700, avgPct: 7.1, maxPct: 12, elevationM: 1848, summitM: 2757, lat: 46.5285, lon: 10.4534, surface: "asfalt", seizoen: "ca. mei–nov, weer-afhankelijk (wintergesloten)", note: "48 haarspelden naar 2757 m vanaf Prato — de heilige graal voor elke motorrijder (zomer geopend).", prompt: "Motorweekend Stelvio: de zuidzijde vanaf Prato en terug over de Umbrailpas, 220 km" },
  { id: "mortirolo", name: "Mortirolo", country: "IT", place: "Mazzo in Valtellina", lengthM: 12400, avgPct: 10.4, maxPct: 18, elevationM: 1300, summitM: 1852, lat: 46.232, lon: 10.296, surface: "asfalt", seizoen: "ca. apr–okt (wintergesloten)", note: "Brutale klim uit de Giro (gem. 10,4%); het monument van Marco Pantani staat op de top.", prompt: "Fiets- of motorrit over de Mortirolo en door de Valtellina, 140 km" },
  { id: "furkapass", name: "Furkapass", country: "CH", place: "Andermatt", lengthM: 12800, avgPct: 7.7, maxPct: 11, elevationM: 949, summitM: 2436, lat: 46.5723, lon: 8.4152, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten; in de winter autotrein door de tunnel)", note: "James Bond-haarspelden (Goldfinger) naar 2436 m; sluit aan op Grimsel en Susten voor de drie-passen-rit.", prompt: "Zwitserse drie-passenrit: Furka, Grimsel en Susten vanuit Andermatt, 190 km" },
  { id: "grossglockner", name: "Grossglockner Hochalpenstrasse", country: "AT", place: "Ferleiten", lengthM: 22000, avgPct: 7, maxPct: 12, elevationM: 1500, summitM: 2504, lat: 47.076, lon: 12.836, surface: "asfalt", seizoen: "ca. mei–begin nov (tolweg, wintergesloten)", note: "Oostenrijks hoogalpijnen meesterwerk naar 2504 m (tolweg, marmotten en gletsjerzicht).", prompt: "Oostenrijk-rit over de Grossglockner Hochalpenstrasse, 180 km, tolweg" },
  { id: "timmelsjoch", name: "Timmelsjoch", country: "AT", place: "Ötztal", lengthM: 29000, avgPct: 7.1, maxPct: 13, elevationM: 2029, summitM: 2509, lat: 46.909, lon: 11.096, surface: "asfalt", seizoen: "ca. jun–okt (tolweg, wintergesloten)", note: "29 km naar 2509 m aan de Italiaanse grens (tolweg); het mooiste hoogtemuseum staat langs de weg.", prompt: "Alpenrit over het Timmelsjoch vanaf het Ötztal naar Zuid-Tirol, 210 km, tolweg" },
  { id: "madeleine", name: "Col de la Madeleine", country: "FR", place: "La Chambre", lengthM: 15300, avgPct: 7.3, maxPct: 10, elevationM: 1120, summitM: 1993, lat: 45.43, lon: 6.383, surface: "asfalt", seizoen: "ca. mei–okt (wintergesloten)", note: "Klassieker tussen Maurienne en Tarentaise met uitzicht op de Belledonne-kam.", prompt: "Alpenrit over de Col de la Madeleine en de Col de l'Iseran, 200 km" },

  { id: "oude-kwaremont", name: "Oude Kwaremont", country: "BE", place: "Kluisbergen", lengthM: 2200, avgPct: 4.2, maxPct: 11, elevationM: 93, summitM: 111, lat: 50.777, lon: 3.514, surface: "kassei", seizoen: "hele jaar — kasseien het best bij droog weer", note: "2600 m totale klim, waarvan 1000 m Vlaamse kassei: de langste kasseistrook van de Ronde.", prompt: "Ronde van Vlaanderen-rit over de Oude Kwaremont en Koppenberg, 110 km" },
  { id: "taaienberg", name: "Taaienberg", country: "BE", place: "Munkzwalm", lengthM: 800, avgPct: 6.2, maxPct: 13, elevationM: 50, summitM: 78, lat: 50.814, lon: 3.618, surface: "kassei", seizoen: "hele jaar — kasseien het best bij droog weer", note: "De favoriete aanvalsheuvel van de Ronde: Boonen en Cancellara maakten hier geschiedenis.", prompt: "Vlaamse Ardennen-rit met de Taaienberg en de Muur van Geraardsbergen, 100 km" },
  { id: "kruisberg", name: "Kruisberg", country: "BE", place: "Ronse", lengthM: 2400, avgPct: 4.8, maxPct: 9, elevationM: 110, summitM: 110, lat: 50.762, lon: 3.608, surface: "asfalt", seizoen: "hele jaar — kasseien het best bij droog weer", note: "Asfalten beklimming bij Ronse, vaste gast tussen Kwaremont en Paterberg in de Ronde.", prompt: "Ronde van Vlaanderen-motorroute met de Kruisberg en de Oude Kwaremont, 120 km" },
  { id: "feldberg", name: "Feldberg (Schwarzwald)", country: "DE", place: "Todtnau", lengthM: 9200, avgPct: 6, maxPct: 10, elevationM: 570, summitM: 1230, lat: 47.874, lon: 8.004, surface: "asfalt", seizoen: "hele jaar — sneeuw mogelijk in de winter", note: "Naar het dak van het Zwarte Woud (1277 m); Schwarzwaldhochstraße sluit aan.", prompt: "Rit over de Feldberg en de Schwarzwaldhochstraße, 220 km" },

  // --- Ronde 32: uitbreiding op geverifieerde climbfinder/organisatie-cijfers ---
  { id: "mont-ventoux", name: "Mont Ventoux (Bédoin)", country: "FR", place: "Bédoin", lengthM: 21500, avgPct: 7.5, maxPct: 12, elevationM: 1600, summitM: 1912, lat: 44.1741, lon: 5.2786, surface: "asfalt", seizoen: "ca. mei–okt (top wintergesloten; mistral het hele jaar)", note: "De Reus van de Provence: 21,5 km aan 7,5% naar 1912 m, met het maanlandschap boven Chalet Reynard.", prompt: "Motorrit over de Mont Ventoux vanaf Bédoin en terug via Malaucène, 150 km" },
  { id: "col-de-la-bonette", name: "Cime de la Bonette", country: "FR", place: "Jausiers", lengthM: 23300, avgPct: 6.8, maxPct: 11.7, elevationM: 1587, summitM: 2802, lat: 44.3217, lon: 6.8064, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten)", note: "De hoogste doorgaande asfaltweg van Europa (2802 m) met 27 haarspelden en een lus rond de top.", prompt: "Alpenrit over de Cime de la Bonette vanaf Jausiers, hoogste weg van Europa, 170 km" },
  { id: "cormet-de-roselend", name: "Cormet de Roselend", country: "FR", place: "Beaufort", lengthM: 20300, avgPct: 6.2, maxPct: 9, elevationM: 1251, summitM: 1969, lat: 45.6870, lon: 6.6790, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten)", note: "Twintig kilometer naar 1969 m met het turkooizen stuwmeer van Roselend als beloning halverwege.", prompt: "Motorrit over de Cormet de Roselend vanaf Beaufort langs het Lac de Roselend, 160 km" },
  { id: "col-de-liseran", name: "Col de l'Iseran", country: "FR", place: "Bonneval-sur-Arc", lengthM: 32200, avgPct: 4.5, maxPct: 10.6, elevationM: 1451, summitM: 2770, lat: 45.4172, lon: 7.0311, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten)", note: "De hoogste bergpas van de Alpen (2770 m) vanaf Lanslebourg: 32 km klimmen door de Haute-Maurienne.", prompt: "Alpenrit over de Col de l'Iseran vanaf Lanslebourg naar Val d'Isère, 180 km" },
  { id: "passo-giau", name: "Passo Giau", country: "IT", place: "Selva di Cadore", lengthM: 9800, avgPct: 9.5, maxPct: 14.7, elevationM: 923, summitM: 2238, lat: 46.4797, lon: 12.0553, surface: "asfalt", seizoen: "ca. mei–okt (wintergesloten)", note: "24 haarspelden aan 9,5% gemiddeld: de zwaarste en fotogeniekste col van de Dolomieten.", prompt: "Dolomieten-motorrit over de Passo Giau en de Falzarego vanaf Cortina, 160 km" },
  { id: "passo-pordoi", name: "Passo Pordoi", country: "IT", place: "Arabba", lengthM: 9200, avgPct: 6.9, maxPct: 10, elevationM: 638, summitM: 2239, lat: 46.4880, lon: 11.8130, surface: "asfalt", seizoen: "ca. mei–okt (wintergesloten)", note: "28 perfecte haarspelden naar 2239 m — Cima Coppi van dertien Giro's, hart van de Sella Ronda.", prompt: "Sella Ronda-motorrit over Pordoi, Sella, Gardena en Campolongo vanaf Arabba, 120 km" },
  { id: "passo-sella", name: "Passo Sella", country: "IT", place: "Canazei", lengthM: 5500, avgPct: 7.9, maxPct: 12, elevationM: 436, summitM: 2244, lat: 46.5100, lon: 11.7620, surface: "asfalt", seizoen: "ca. mei–okt (wintergesloten)", note: "Korte scherpe klim naar 2244 m recht onder de rotswanden van de Sassolungo.", prompt: "Dolomieten-rondrit over de Passo Sella en Passo Gardena vanaf Canazei, 110 km" },
  { id: "passo-gavia", name: "Passo di Gavia", country: "IT", place: "Ponte di Legno", lengthM: 16400, avgPct: 8, maxPct: 14.6, elevationM: 1319, summitM: 2622, lat: 46.3436, lon: 10.4917, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten, smalle weg)", note: "Smalle, wilde Giro-legende naar 2622 m — steiler en ruiger dan de Stelvio ernaast.", prompt: "Motorrit over de Passo Gavia en de Stelvio vanaf Ponte di Legno, 180 km" },
  { id: "grimselpass", name: "Grimselpass", country: "CH", place: "Innertkirchen", lengthM: 26300, avgPct: 5.8, maxPct: 10.4, elevationM: 1534, summitM: 2164, lat: 46.5610, lon: 8.3400, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten)", note: "Granietwereld met stuwmeren naar 2164 m; onderdeel van de klassieke drie-passenrit met Furka en Susten.", prompt: "Zwitserse drie-passenrit: Grimsel, Furka en Susten vanaf Innertkirchen, 190 km" },
  { id: "sustenpass", name: "Sustenpass", country: "CH", place: "Wassen", lengthM: 17400, avgPct: 7.5, maxPct: 11.2, elevationM: 1307, summitM: 2224, lat: 46.7280, lon: 8.4470, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten)", note: "Volgens veel motorrijders de mooiste pasweg van Zwitserland: brede bochten, tunnels en gletsjerzicht op 2224 m.", prompt: "Motorrit over de Sustenpass van Wassen naar Innertkirchen, 150 km" },
  { id: "klausenpass", name: "Klausenpass", country: "CH", place: "Bürglen", lengthM: 23900, avgPct: 6.4, maxPct: 19.2, elevationM: 1530, summitM: 1948, lat: 46.8690, lon: 8.8580, surface: "asfalt", seizoen: "ca. mei–okt (wintergesloten)", note: "Bijna 24 km naar 1948 m door het Schächental, met de steilste rampen van de Zwitserse passen.", prompt: "Motorrit over de Klausenpass van Bürglen naar Linthal, 140 km" },
  { id: "nufenenpass", name: "Nufenenpass", country: "CH", place: "Ulrichen", lengthM: 13700, avgPct: 8.3, maxPct: 11.6, elevationM: 1132, summitM: 2478, lat: 46.4780, lon: 8.3880, surface: "asfalt", seizoen: "ca. jun–okt (wintergesloten)", note: "De hoogste volledig Zwitserse pas (2478 m): negen kilometer boven de boomgrens aan 9%.", prompt: "Alpenrit over de Nufenenpass, Gotthard en Furka vanaf Ulrichen, 170 km" },
  { id: "mur-de-huy", name: "Mur de Huy", country: "BE", place: "Huy", lengthM: 1400, avgPct: 9.7, maxPct: 16.4, elevationM: 136, summitM: 206, lat: 50.5230, lon: 5.2450, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "De finish van de Waalse Pijl: de Chemin des Chapelles met bochten tot 20% vlak boven de Maas.", prompt: "Rit door de Condroz over de Mur de Huy en de Maasvallei, 120 km" },
  { id: "kemmelberg", name: "Kemmelberg", country: "BE", place: "Kemmel", lengthM: 500, avgPct: 11.8, maxPct: 15.9, elevationM: 55, summitM: 156, lat: 50.7880, lon: 2.8180, surface: "kassei", seizoen: "hele jaar — kasseien het best bij droog weer", note: "De kasseimuur van Gent-Wevelgem in de Westhoek, met het Belvédère en de oorlogsgeschiedenis van 1918.", prompt: "Rit door de Westhoek over de Kemmelberg en de Heuvelland-kasseien, 100 km" },
  { id: "keutenberg", name: "Keutenberg", country: "NL", place: "Schin op Geul", lengthM: 1600, avgPct: 5.5, maxPct: 16.7, elevationM: 88, summitM: 167, lat: 50.8330, lon: 5.8770, surface: "asfalt", seizoen: "hele jaar — in de winter soms glad", note: "Het beruchte 22%-bordje: de steilste eerste 400 meter van Nederland, daarna een plateau naar Berghof.", prompt: "Fietsrit door het Geuldal over de Keutenberg en de Cauberg, 70 km" },

];
